/**
 * SQL Injection Lab: Login - Main Client Controller
 *
 * This script controls:
 * 1. Mode switching between Vulnerable and Secure representations.
 * 2. Communication with the backend (or fake-api for offline development).
 * 3. Sanitized HTML rendering of executed SQL queries with exact user input highlighted.
 * 4. Structured authentication result display with security badges.
 * 5. Event dispatching ('lab:result' and 'lab:reset') for modular teammate integration.
 */

// Toggle between mock browser API (true) and real Docker backend (false)
const USE_FAKE = true;

// DOM Element references
const modeStrip = document.getElementById('mode-strip');
const modeStripLabel = document.getElementById('mode-strip-label');
const modeStripDesc = document.getElementById('mode-strip-desc');
const modeVulnerableRadio = document.getElementById('mode-vulnerable');
const modeSecureRadio = document.getElementById('mode-secure');

const loginForm = document.getElementById('login-form');
const usernameInput = document.getElementById('username');
const passwordInput = document.getElementById('password');
const btnLogin = document.getElementById('btn-login');
const btnReset = document.getElementById('btn-reset');
const exampleButtons = document.querySelectorAll('.btn-example');

const resultBox = document.getElementById('result-box');
const sqlDisplay = document.getElementById('sql-display');

/**
 * HTML sanitization helper to prevent XSS (Cross-Site Scripting).
 * Viva explanation:
 * Any user input injected into innerHTML must be encoded so that characters
 * like <, >, &, ", and ' are not interpreted by the browser as HTML tags.
 *
 * @param {string} str - Raw string to escape
 * @returns {string} - Escaped string safe for innerHTML
 */
function escapeHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * Returns the currently active mode ("vulnerable" or "secure")
 */
function getSelectedMode() {
  return modeSecureRadio.checked ? 'secure' : 'vulnerable';
}

/**
 * Updates the top coloured strip and UI elements when the mode changes.
 * Viva explanation:
 * - Amber for Vulnerable: dynamic SQL concatenation can allow query manipulation.
 * - Teal for Secure: parameterized SQL separates code execution from untrusted data.
 *
 * @param {string} mode - "vulnerable" or "secure"
 */
function updateModeUI(mode) {
  if (mode === 'vulnerable') {
    modeStrip.className = 'mode-strip mode-vulnerable';
    modeStripLabel.textContent = 'Vulnerable mode';
    modeStripDesc.textContent = 'The server builds the SQL by joining your text into it.';
  } else {
    modeStrip.className = 'mode-strip mode-secure';
    modeStripLabel.textContent = 'Secure mode';
    modeStripDesc.textContent = 'The server sends your text as data, separate from the SQL.';
  }
}

/**
 * Renders the SQL query in the dark code box.
 * Viva explanation:
 * - In Vulnerable mode, the user input is concatenated directly. We wrap the exact
 *   typed input in <mark class="mark-vuln"> to demonstrate how attacker input
 *   becomes part of the executable SQL grammar (e.g. quotes closing literals, -- commenting).
 * - In Secure mode, the query uses fixed placeholders ($1, $2). The user text is
 *   transmitted in a separate parameter stream, shown below the query.
 *
 * @param {string} mode - "vulnerable" or "secure"
 * @param {string} username - User typed username
 * @param {string} password - User typed password
 */
function renderSqlDisplay(mode, username, password) {
  const safeUser = escapeHtml(username);
  const safePass = escapeHtml(password);

  if (mode === 'vulnerable') {
    sqlDisplay.innerHTML = `<code><span class="sql-keyword">SELECT</span> * <span class="sql-keyword">FROM</span> users <span class="sql-keyword">WHERE</span> username='<mark class="mark-vuln">${safeUser}</mark>' <span class="sql-keyword">AND</span> password='<mark class="mark-vuln">${safePass}</mark>'</code>`;
  } else {
    sqlDisplay.innerHTML = `<code><span class="sql-keyword">SELECT</span> * <span class="sql-keyword">FROM</span> users <span class="sql-keyword">WHERE</span> username = $1 <span class="sql-keyword">AND</span> password = $2</code>` +
      `<div class="sql-params-note">` +
      `Sent separately as data: $1 = <mark class="mark-sec">${safeUser}</mark>, $2 = <mark class="mark-sec">${safePass}</mark>` +
      `</div>`;
  }
}

/**
 * Badge configuration for the 4 distinct lab states.
 * Viva explanation:
 * - vulnerable-bypass (Red): Injection succeeded; attacker altered query structure.
 * - blocked (Teal): Parameterization preserved security; input treated as literal string.
 * - error (Amber): Malformed SQL syntax generated by unbalanced quote.
 * - normal (Grey): Standard legitimate authentication check succeeded or failed normally.
 */
const BADGE_MAP = {
  'vulnerable-bypass': {
    text: 'Injection worked: your text changed the query',
    className: 'badge-bypass'
  },
  'blocked': {
    text: 'Input treated as plain text',
    className: 'badge-blocked'
  },
  'error': {
    text: 'The database rejected the query',
    className: 'badge-error'
  },
  'normal': {
    text: 'Normal behaviour',
    className: 'badge-normal'
  }
};

/**
 * Renders the authentication outcome inside the Result card.
 *
 * @param {Object} response - The API response object
 * @param {boolean} response.success - Whether authentication was granted
 * @param {string} response.message - Explanatory message
 * @param {string} response.status - Status code ("vulnerable-bypass", "blocked", "error", "normal")
 * @param {Array} response.rows - Returned database records
 */
function renderResultBox(response) {
  const isSuccess = Boolean(response.success);
  const status = response.status || 'normal';
  const badgeInfo = BADGE_MAP[status] || BADGE_MAP['normal'];

  // Determine headline
  let headlineText = isSuccess ? 'Login successful' : 'Login failed';
  let headlineClass = isSuccess ? 'success' : (status === 'error' ? 'error' : 'failed');

  // Format who is logged in
  const rows = Array.isArray(response.rows) ? response.rows : [];
  const rowCount = rows.length;

  let loggedInText = 'None (unauthenticated)';
  if (rows.length > 0) {
    loggedInText = rows.map((r) => `${escapeHtml(r.username)} (${escapeHtml(r.role)})`).join(', ');
  }

  resultBox.innerHTML = `
    <div class="result-content">
      <div class="result-header-row">
        <h3 class="result-headline ${headlineClass}">${escapeHtml(headlineText)}</h3>
        <span class="badge ${badgeInfo.className}">${escapeHtml(badgeInfo.text)}</span>
      </div>

      <p class="result-message">${escapeHtml(response.message || '')}</p>

      <div class="result-details-grid">
        <span class="result-label">Logged in as:</span>
        <span class="result-value">${loggedInText}</span>

        <span class="result-label">Rows returned:</span>
        <span class="result-value">${rowCount} ${rowCount === 1 ? 'row' : 'rows'}</span>
      </div>
    </div>
  `;
}

/**
 * Displays a helpful offline / network error state when the backend server is unreachable.
 */
function renderNetworkError() {
  resultBox.innerHTML = `
    <div class="network-error-card">
      <div class="result-header-row">
        <h3 class="result-headline failed">Cannot reach the lab server</h3>
        <span class="badge badge-error">Offline</span>
      </div>
      <p class="result-message">The frontend could not connect to the backend API. Please run:</p>
      <pre><code>docker compose up --build</code></pre>
    </div>
  `;

  sqlDisplay.innerHTML = `<span class="sql-placeholder">-- Query failed to reach database</span>`;
}

/**
 * Resets the output cards to their clean default state.
 */
function clearOutputs() {
  resultBox.innerHTML = `<div class="result-empty">Submit credentials to see query execution and authentication results.</div>`;
  sqlDisplay.innerHTML = `<span class="sql-placeholder">-- No query executed yet</span>`;
}

/**
 * Submits login request to either fake-api or live server.
 *
 * @param {string} username - User input username
 * @param {string} password - User input password
 * @param {string} mode - "vulnerable" or "secure"
 */
async function handleLogin(username, password, mode) {
  // First, render the query in the code box so the student sees the SQL
  renderSqlDisplay(mode, username, password);

  try {
    let responseData;

    if (USE_FAKE) {
      // Offline mock backend
      responseData = await fakeLogin(username, password, mode);
    } else {
      // Live backend HTTP request
      const response = await fetch('/api/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password, mode })
      });

      if (!response.ok) {
        try {
          responseData = await response.json();
        } catch {
          throw new Error(`Server returned HTTP ${response.status}`);
        }
      } else {
        responseData = await response.json();
      }
    }

    // Render result cards
    renderResultBox(responseData);

    // Dispatch custom event for teammate extensions (Query visualizer & Activity log)
    // Viva explanation: CustomEvent decouples components, allowing teammates to add
    // live telemetry or AST query visualization without modifying this file.
    document.dispatchEvent(
      new CustomEvent('lab:result', {
        detail: {
          time: new Date().toISOString(),
          mode,
          username,
          password,
          ...responseData
        }
      })
    );
  } catch (err) {
    console.error('Login request failed:', err);
    renderNetworkError();
  }
}

/**
 * Resets lab state.
 */
async function handleReset() {
  loginForm.reset();
  // Ensure default mode is reset to vulnerable
  modeVulnerableRadio.checked = true;
  updateModeUI('vulnerable');

  clearOutputs();

  try {
    if (USE_FAKE) {
      if (typeof fakeReset === 'function') {
        await fakeReset();
      }
    } else {
      await fetch('/api/reset', { method: 'POST' });
    }
  } catch (err) {
    console.warn('Backend reset call encountered an issue:', err);
  }

  // Dispatch custom reset event for teammate extensions
  document.dispatchEvent(new CustomEvent('lab:reset'));
}

// Event Listeners
modeVulnerableRadio.addEventListener('change', () => updateModeUI('vulnerable'));
modeSecureRadio.addEventListener('change', () => updateModeUI('secure'));

loginForm.addEventListener('submit', (event) => {
  event.preventDefault();
  const username = usernameInput.value;
  const password = passwordInput.value;
  const mode = getSelectedMode();
  handleLogin(username, password, mode);
});

btnReset.addEventListener('click', handleReset);

// Example input buttons handler
exampleButtons.forEach((btn) => {
  btn.addEventListener('click', () => {
    const user = btn.getAttribute('data-user') || '';
    const pass = btn.getAttribute('data-pass') || '';

    usernameInput.value = user;
    passwordInput.value = pass;
    usernameInput.focus();
  });
});

// Initial setup on page load
updateModeUI(getSelectedMode());
